# Generated by Django 6.0.6 on 2026-07-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField()),
                ('muallif', models.CharField()),
                ('yil', models.IntegerField()),
                ('janri', models.CharField(choices=[('roman', 'Roman'), ('qissa', 'Qissa'), ('hikoya', 'Hikoya'), ('ertak', 'Ertak')])),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
