# Generated by Django 6.0.6 on 2026-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField()),
                ('tavsifi', models.TextField()),
                ('tayyorlash_vaqti', models.IntegerField()),
                ('muallif', models.CharField()),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-yaratilgan_sana'],
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
